### ISSUE TITLE
Can't run in electron with windows 11

### ISSUE THREAD

**Issue by dongnaebi** [LaunchMenu/node-global-key-listener#38] opened 2024-03-31 16:52 UTC
v.addListener cause an error:

```
[Window Title]
Error

[Main Instruction]
A JavaScript error occurred in the main process

[Content]
Uncaught Exception:
Error: spawn E:\rotick\bin\WinKeyServer.exe ENOENT
    at ChildProcess._handle.onexit (node:internal/child_process:286:19)
    at onErrorNT (node:internal/child_process:484:16)
    at process.processTicksAndRejections (node:internal/process/task_queues:82:21)
```

**Comment by sancarn** [comment] 2024-04-02 09:24
Probably a duplicate of #13

**Closed by sancarn** 2024-04-02 09:24 UTC
