### ISSUE TITLE
Library does not work on Apple Chip

### ISSUE THREAD

**Issue by olan-go2** [LaunchMenu/node-global-key-listener#43] opened 2024-06-05 15:43 UTC
The library works well in build using x64, but not arm64 which the Apple Chip uses. Can we add support for this, please? Thank you.

**Comment by sancarn** [comment] 2024-06-05 23:28
I believe this is a duplicate of #36. Happy to accept a PR.

**Closed as completed by sancarn** 2024-06-05 23:28 UTC

**Comment by olan-go2** [comment] 2024-06-06 10:42
This library is the most available and works perfectly atm. I'm not familiar for any native development.
